apiVersion: 1

contactPoints:
  - orgId: 1
    name: grafana-default-email
    receivers:
      - uid: default-email
        type: email
        settings:
          addresses: admin@localhost
          subject: "Grafana Alert: {{ .GroupLabels.alertname }}"
          body: |
            Alert: {{ .GroupLabels.alertname }}
            Status: {{ .Status }}
            
            {{ range .Alerts }}
            Summary: {{ .Annotations.summary }}
            Description: {{ .Annotations.description }}
            Labels: {{ range .Labels.SortedPairs }}{{ .Name }}={{ .Value }} {{ end }}
            {{ end }}
        disableResolveMessage: false

  - orgId: 1  
    name: webhook-placeholder
    receivers:
      - uid: webhook-placeholder
        type: webhook
        settings:
          url: http://localhost:8080/webhook
          username: ""
          password: ""
          title: "Grafana Alert"
          httpMethod: POST
        disableResolveMessage: false