apiVersion: 1

policies:
  - orgId: 1
    receiver: grafana-default-email
    group_by: 
      - alertname
      - grafana_folder
    group_wait: 10s
    group_interval: 5m
    repeat_interval: 12h
    routes:
      - receiver: grafana-default-email
        object_matchers:
          - - severity
            - "="
            - critical
        group_wait: 5s
        group_interval: 1m
        repeat_interval: 30m
        continue: false
      
      - receiver: grafana-default-email  
        object_matchers:
          - - severity
            - "="
            - warning
        group_wait: 30s
        group_interval: 5m
        repeat_interval: 2h
        continue: false