services:
  caddy:
    image: caddy:latest
    container_name: caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./settings:/etc/caddy
      - ./static:/srv/static
      - ./caddy_data:/data
      - ./caddy_config:/config
    restart: unless-stopped
    networks:
      - caddy_net

networks:
  caddy_net: # Crete VPN internal - Need to bind running containers to this network as well
    driver: bridge
